### PR TITLE
Added OS prep script for Ubuntu, modified directory structure

### PR DESCRIPTION
**Pull request by rajcrk**
I have added in OS prep script for Ubuntu (Hurray !), which will install the following developer tools and applications.
Made assumptions about the developer tools and applications that we would need based on the pre-existing script `osxprep.sh`
- git
- curl
- wget
- docker
- vim
- openssh
- php
- heroku
- virtualbox
- java
- sublime-text-3
- atom

The modifications to the directory structure are made so that we could have more OS prep scripts added in the nearby awesome future. Do let me know your thoughts on them.

### CODE REVIEW

**Comment by xlogix** [comment]
Looks good!

**Comment by xlogix** [comment]
I think there is a duplicate file for osx. Can you delete one?

**Comment by rajcrk** [comment]
My bad @xlogix, Forgot to commit that 😅. Will remove that in the next pull request ( possibly when adding in additional developer tools for ubuntu ).

**Comment by xlogix** [comment]
No issues! :)

**Pull request merged**
